{{- if and .Values.concierge.podDisruptionBudget.enabled (gt .Values.concierge.replicaCount 1.0) -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ditto.fullname" . }}-concierge
  labels:
    app.kubernetes.io/name: {{ include "ditto.name" . }}-concierge
{{ include "ditto.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ditto.name" . }}-concierge
      app.kubernetes.io/instance: {{ .Release.Name }}
  minAvailable: {{ .Values.concierge.podDisruptionBudget.minAvailable }}
{{- end }}
