{{- if and .Values.gateway.podDisruptionBudget.enabled (gt .Values.gateway.replicaCount 1.0) -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ditto.fullname" . }}-gateway
  labels:
    app.kubernetes.io/name: {{ include "ditto.name" . }}-gateway
{{ include "ditto.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ditto.name" . }}-gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
  minAvailable: {{ .Values.gateway.podDisruptionBudget.minAvailable }}
{{- end }}
