{{- if .Values.nginx.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $name := include "ditto.name" . -}}
{{- $labels := include "ditto.labels" . -}}
{{ $root := . }}
{{ range $path, $bytes := .Files.Glob "nginx-config/**" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $path | replace "/" "-" | replace "." "-" }}
  labels:
    app.kubernetes.io/name: {{ $name }}-nginx-config
{{ $labels | indent 4 }}
data:
  {{ $path | replace "nginx-config/" ""}}: |-
{{ $root.Files.Get $path | indent 4 }}
---
{{- end -}}
{{- end }}
