{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ditto.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "ditto.name" . }}
{{ include "ditto.labels" . | indent 4 }}
{{- end -}}
