apiVersion: v1
appVersion: "1.0.0-M3"
description: A Helm chart for Eclipse Ditto
name: ditto
version: 1.0.0-snapshot
home: https://www.eclipse.org/ditto
sources:
- https://github.com/eclipse/ditto
- https://github.com/eclipse/packages
icon: https://www.eclipse.org/ditto/images/ditto.svg
maintainers:
- name: axdotl
  email: axel.koehler@kiwigrid.com
- name: thjaeckle
  email: thomas.jaeckle@bosch-si.com
